name: Patch version
on:
  push:
    branches:
      - dev

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  patch:
    name: ðŸ“¦ Patch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
      - name: ðŸ” GH_TOKEN
        if: env.GH_TOKEN == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
      - name: ðŸ¤˜Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: âš™ Setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: ðŸ“¦Patch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          npm run prepPatch
          git push