name: Patch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run scripts
        shell: bash
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done

      - name: Install
        run: npm install

      - name: Test
        run: npm test

  patch:
    name: Patch version
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upgrade version
        env:
          GIT_DEPLOYER_EMAIL: ${{ secrets.GIT_DEPLOYER_EMAIL }}
        run:  |
          git config --global user.name 'Workflow deployer'
          git config --global user.email '$GIT_DEPLOYER_EMAIL'
          npm version patch -m "Patch to %s"

      - name: Commit version
        run: |
          git commit -am "Upgrade version"
          git push

  build:
    name: Code QL and build
    needs: patch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Run scripts
        shell: bash
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
