# - Publishes the build of the master branch to GitHub pages
# - Updates the version based on the tag chosen in the GitHub release flow

name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  set-version:
    name: Update version and deploy
    runs-on: ubuntu-latest
    steps:
      - name: "â˜ï¸ checkout repository"
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: "ğŸ”§ setup node"
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: "ğŸ“¦ update version"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          npm version $GITHUB_REF_NAME
          git push
          npm ci
          npm run build

      - name: "ğŸš€ deploy to GitHub Pages"
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build